name: Trigger auto deployment for Azure Container Apps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    
    paths:
      - "/Users/mahmoudelzayet/mbp/demo/azure-cn-depicted/01.Platform/Container Apps/**"
      - ".github/workflows/aca-deploy.yml"

  # Allow manually trigger 
  workflow_dispatch:      

permissions:
      id-token: write
      contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3
      
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEPLOY_IDENTITY_CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Deploy ACA Bicep
        uses: azure/CLI@v1
        with:
          azcliversion: 2.41.0
          inlineScript: |
            az deployment group create -n aca-deploy -g ${{ secrets.ACA_RG }} --template-file 01.Platform/Container Apps/bicep/ca-env.bicep --parameters containerAppsEnvName=${{ secrets.ACA_ENV_NAME }}
    
      
      